// source: https://www.chartjs.org/docs/latest/getting-started/
// helpful link: https://stackoverflow.com/questions/37621020/setting-width-and-height
// another one: https://stackoverflow.com/questions/20206038/converting-chart-js-canvas-chart-to-image-using-todataurl-results-in-blank-im
const ctx = document.getElementById('myChart').getContext('2d');
const myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: [
         "Extract Function",
         "Change Fn Declaration",
         "Inline Function",
         "Move Function",
         "Inline Variable",
         "Encapsulate Variable",
         "Extract Class",
         "Slide Statements",
         "Replace Conditional with Polymorphism",
         "Remove Dead Code",
         "Pull Up Method",
         "Combine Functions into Class",
         "Introduce Assertion",
         "Replace Paramter with Query",
         "Replace Constructor with Factory Function",
         "Remove Setting Method",
         "Extract Variable",
         "Encapsulate Record",
         "Split Variable",
         "Replace Temp with Query",
         "Split Phase",
         "Pull Up Field",
         "Move Staments to Callers",
         "Introduce Paramter Object",
         "Change Referance to Value",
         "Replace Type Code with Subclasses",
         "Push Down Method",
         "Move Field",
         "Hide Delegate",
         "Extract Superclass",
         "Combine Functions into Transform",
         "Change Value to Reference",
         "Replace Superclass with Delegate",
         "Replace Loop with Pipeline",
         "Push Down Field",
         "Inline Class",
         "Decompose Conditional",
         "Split Loop",
         "Separate Query from Modifier",
         "Replace Subclass with Delegate",
         "Replace Primitive with Object",
         "Rename Variable",
         "Preserve Whole Object",
         "Parameterize Function",
         "Substitute Algorithm",
         "Replace Function with Command",
         "Remove Middle Man",
         "Pull Up Constructor Body",
         "Introduce Special Case",
         "Encapsulate Collection",
         "Consolidate Conditional Expression",
         "Collapse Hierarchy",
         "Replace Query with Paramter",
         "Replace Inline Code with Function",
         "Replace Derived Variable with Query",
         "Replace Command with Function",
         "Rename Field",
         "Remove Subclass",
         "Remove Flag Argument",
         "Move Statements into Function",
         "Replace Nested Conditional with Guard Clauses"
        ],
        datasets: [{
            label: '# of References',
            data: [
             85,
             45,
             34,
             32,
             18,
             18,
             14,
             13,
             13,
             12,
             12,
             12,
             10,
             9,
             9,
             9,
             9,
             9,
             8,
             8,
             7,
             7,
             7,
             7,
             7,
             6,
             6,
             6,
             6,
             6,
             6,
             6,
             5,
             5,
             5,
             5,
             5,
             4,
             4,
             4,
             4,
             4,
             4,
             4,
             3,
             3,
             3,
             3,
             3,
             3,
             3,
             3,
             2,
             2,
             2,
             2,
             2,
             2,
             2,
             2,
             1
            ],
            backgroundColor: 'blue'
        }]
    },
    options: {
        // responsive: true,
        // maintainAspectRatio: false,
        // animation: {
        //   duration: 0 // general animation time
        // },
        responsive: true,
        maintainAspectRatio: false,
        animation: {
          onComplete: function(animation) {
            createImage(myChart, 1900, 1500);
          },
          duration: 1,
        },
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
